# Generated by Django 5.1.4 on 2026-05-02 07:32

import django.core.validators
import django.db.models.deletion
import od.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ODCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'od_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ODRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_type', models.CharField(choices=[('sports', 'Sports'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('internship', 'Internship'), ('placement', 'Placement'), ('cultural event', 'Cultural Event'), ('technical event', 'Technical Event'), ('NSS/NCC', 'NSS/NCC'), ('other', 'Other')], max_length=30)),
                ('event_title', models.CharField(max_length=180)),
                ('reason', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('place', models.CharField(max_length=180)),
                ('organizer_details', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_FACULTY_REVIEW', 'Pending Faculty Review'), ('FACULTY_APPROVED', 'Faculty Approved'), ('FORWARDED_TO_DEAN', 'Forwarded to Dean'), ('DEAN_APPROVED', 'Dean Approved'), ('DEAN_REJECTED', 'Dean Rejected'), ('FACULTY_REJECTED', 'Faculty Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_FACULTY_REVIEW', max_length=40)),
                ('faculty_approved_at', models.DateTimeField(blank=True, null=True)),
                ('dean_approved_at', models.DateTimeField(blank=True, null=True)),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dean_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_approved_ods', to=settings.AUTH_USER_MODEL)),
                ('faculty_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_approved_ods', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_requests', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'od_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ODApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING_FACULTY_REVIEW', 'Pending Faculty Review'), ('FACULTY_APPROVED', 'Faculty Approved'), ('FORWARDED_TO_DEAN', 'Forwarded to Dean'), ('DEAN_APPROVED', 'Dean Approved'), ('DEAN_REJECTED', 'Dean Rejected'), ('FACULTY_REJECTED', 'Faculty Rejected'), ('CANCELLED', 'Cancelled')], max_length=40)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('od_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='od.odrequest')),
            ],
            options={
                'db_table': 'od_approvals',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=od.models.secure_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), od.models.validate_upload_size])),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('od_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='od.odrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ODRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days_per_month', models.PositiveIntegerField(default=5)),
                ('max_days_per_semester', models.PositiveIntegerField(default=20)),
                ('allow_past_dates', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='od_rules', to='accounts.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_rules', to='accounts.school')),
            ],
            options={
                'db_table': 'od_rules',
                'ordering': ['school__name', 'department__name'],
                'unique_together': {('school', 'department')},
            },
        ),
    ]
